name: "machine_dbt"
version: "1.0.0"
config-version: 2

profile: "machine_dbt"

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]

models:
  machine_dbt:
    +materialized: view

    silver:
      +materialized: incremental
    gold:
      +materialized: table
